# Config file for automatic testing at travis-ci.org

language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOX_ENV='flake8'
    - python: 3.5
      env: TOX_ENV='isort'
    # Django 1.11
    - python: 3.5
      env: DJANGO='dj111' CMS='cms35'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms36'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms37'
    - python: 3.5
      env: DJANGO='dj111' CMS='cms40'
    # Django 2.1
    - python: 3.6
      env: DJANGO='dj21' CMS='cms35'
    - python: 3.6
      env: DJANGO='dj21' CMS='cms36'
    - python: 3.6
      env: DJANGO='dj21' CMS='cms37'
    - python: 3.6
      env: DJANGO='dj21' CMS='cms40'
    # Django 2.2
    - python: 3.7
      env: DJANGO='dj22' CMS='cms35'
    - python: 3.7
      env: DJANGO='dj22' CMS='cms36'
    - python: 3.7
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.7
      env: DJANGO='dj22' CMS='cms40'
      dist: xenial
      sudo: true
    - python: 3.8
      env: DJANGO='dj22' CMS='cms40'

before_script:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

install:
  - pip install -U tox>=1.8 coveralls codecov wheel pip
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"
  - "if [[ $FE == 1 ]]; then export FE_STR='-fe'; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls

cache:
   directories:
     - $HOME/.pip-accel
     - $HOME/.cache/pip
